version: '3'
services:
 apache:
   image: 420698008/apachemysql:latest
   restart: always
   tty: true
   ports:
     - ${PORT}:80
     - "3306:3306"
   volumes:
     - ./web:/var/ww/html
  
