version: "3"
services:
  www:
      image: gabrielkarapetian1/apache
      ports:
          - ${PORT}:80
      links:
          - db
  db:
     image: mysql
     environment:
       MYSQL_ROOT_PASSWORD: P@ssw0rd
       MYSQL_USER: DB_USER
       MYSQL_PASSWORD: DB_PASSWORD
       MYSQL_DATABASE: database
     ports:
       - ${PORT-MYSQL}:3306

