
version: '2'
services:
   users_db:
    image: gabrielkarapetian1/couchdb
    ports:
      - '3000:5984'
   auth_ms:
    image: gabrielkarapetian1/auth
    environment:
      DB_PORT: '5984'
      DB_URL: 'users_db'
      JWT_SECRET: ${PASS_AUTH} # Put your own secret!
    ports:
      - ${PORT_AUTH}:4005
    links:
      - users_db
  www:
      image: gabrielkarapetian1/apache
      ports:
          - ${PORT_APACHE}:80
      links:
          - db
  db:
     image: mysql
     environment:
       MYSQL_ROOT_PASSWORD: P@ssw0rd
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASSWORD}
       MYSQL_DATABASE: database
     ports:
       - "5656:3306"

