
version: '3'
services:
 apache:
  image: httpd:latest
  ports:
    - "8080:80"
 db:
  image: mysql:latest
  command: --default-authentication-plugin=mysql_native_password
  environment:
    MYSQL_ROOT_PASSWORD: Adios01!
 openldap:
  image: osixia/openldap:latest
  ports:
    - "389:389"
    - "639:639"




