
version: '2'
services:
   users_db:
    image: gabrielkarapetian1/couchdb
    ports:
      - 3000:5984
   auth_ms:
    image: gabrielkarapetian1/auth
    environment:
      DB_PORT: '5984'
      DB_URL: users_db
      JWT_SECRET: 'P@ssw0rd'
    ports:
      - '4005:4005'
    links:
      - users_db
  
