version: '3.1'
services:
  humhub:
    image: gabrielkarapetian1/humhub_kubernetes:latest
    ports:
      - ${PORT}:80
    environment:
      HUMHUB_DB_USER: ${HUMHUB_DB_USER}
      HUMHUB_DB_PASSWORD: ${HUMHUB_DB_PASSWORD}
      HUMHUB_DB_HOST: 'db'
      HUMHUB_DB_NAME: 'humhub'
      HUMHUB_AUTO_INSTALL: 1
      HUMHUB_DEBUG: 1
      HUMHUB_PROTO: 'https'
      HUMHUB_HOST: 'localhost'

  db:
    image: gabrielkarapetian1/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: 'humhub'
      MYSQL_USER: ${HUMHUB_DB_USER}
      MYSQL_PASSWORD: ${HUMHUB_DB_PASSWORD}
 
