version: '3.1'
services:
  alfresco:
    image: gabrielkarapetian1/alfresco:latest
    links:
      - postgresql:postgresql
    ports:
      - "21:21"
      - "137:137"
      - "138:138"
      - "139:139"
      - "445:445"
      - "7070:7070"
      - "8009:8009"
      - "8080:8080"
    environment:
      CONTENT_STORE: /content
      DB_HOST: postgresql
      DB_KIND: postgresql
      DB_NAME: alfresco
      DB_PASSWORD: ${ALFRESCO_DB_PASSWORD}
      DB_USERNAME: ${ALFRESCO_DB_USER}
    volumes:
      - /alfresco/alf_data
      - /alfresco/tomcat/logs
      - /content
  postgresql:
    image: postgres:9.4
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_PASSWORD: ${ALFRESCO_DB_PASSWORD}
      POSTGRES_USER: ${ALFRESCO_DB_USER}
    volumes:
      - /var/lib/postgresql/data