version: '3'
services:
   terminalserver:
     image: gabrielkarapetian1/linux2
     ###container_name: uxrdp
     hostname: terminalserver
     restart: always
     shm_size: 1g
     environment:
        PASSWORDHASH: $$1$$z53Cg/fV$$06o379IvIOxj/ESruVKrG1
        IDLETIME: 11
     ports:
       
       - "3333:3389"
     volumes:
       
       - /home/:/home/
   db:
     image: mysql
     environment:
       MYSQL_ROOT_PASSWORD: P@ssw0rd
       MYSQL_USER: DB_USER
       MYSQL_PASSWORD: DB_PASSWORD
       MYSQL_DATABASE: database
     ports:
       - 6677:3306    

volumes:
  ssh:
