version: '3.5'
services:
  terminalserver:
    image: gabrielkarapetian1/linux2
    container_name: uxrdp
    hostname: terminalserver
    restart: always
    shm_size: 1g
    environment:
       PASSWORDHASH: $$1$$z53Cg/fV$$06o379IvIOxj/ESruVKrG1
       IDLETIME: 11
    ports:
      - "3389:3389"
      - "2222:22"
    volumes:
      - ssh:/etc/ssh/
      - /home/:/home/
   db:
     image: mysql
     environment:
       MYSQL_ROOT_PASSWORD: P@ssw0rd
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASSWORD}
       MYSQL_DATABASE: database
     ports:
       - ${PORT-MYSQL}:3306    

volumes:
  ssh:
